application: greentea-iidx
version: 0
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /style\.css
  static_files: public/style.css
  upload: public/style\.css

- url: /script\.js
  static_files: public/script.js
  upload: public/script\.js

- url: /anim\.gif
  static_files: public/anim.gif
  upload: public/anim\.gif

#- url: /.*\.(css|js|html)
#  static_files: /public/\1
#  upload: /public/.*\.(css|js|html)
- url: /_ah/login_required
  script: do_openid_login.app

- url: .*
  script: main.app